[package]
name = "rust_hex_editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.8"
rand = "0.8.4"
druid = "0.8.3"
rfd = "0.14.0"
goblin = "0.8"
reverse_engineering_lib = '0.1.0'
